CREATE OR REPLACE FUNCTION multiply_three(x DOUBLE PRECISION, y DOUBLE PRECISION, z DOUBLE PRECISION)
RETURNS DOUBLE PRECISION 
LANGUAGE plpgsql AS
$$
BEGIN
    RETURN x * y * z;
END;
$$ ;

SELECT multiply_three(2, 3, 4);
