CREATE OR REPLACE FUNCTION multiply_three(x DOUBLE PRECISION, y DOUBLE PRECISION, z DOUBLE PRECISION)
RETURNS DOUBLE PRECISION AS $$
BEGIN
    RETURN x * y * z;
END;
$$ LANGUAGE plpgsql;


SELECT multiply_three(2, 3, 4);
